name: CI/CD Pipline Main

on: 
  pull_request:
    branches:
      - Main
    types: [opened]
jobs:
  build-deploy:
    name: build and depoy
    runs-on: self-hosted-main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t test:1 .
      - name: Run Docker Container
        run: docker run -d -p 80:80 test:1
