name: CI/CD Pipline

on: 
  push:
    branches:
      - Develop
jobs:
  check-code:
    name: Check code
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  build-deploy:
    name: build and depoy
    runs-on: self-hosted
    steps:
      - name: Build Docker Image
        run: docker build -t test:1 .
      - name: Run Docker Container
        run: docker run -d -p 80:80 --name kurs test:1
