name: CI/CD Pipline

on: 
  push:
    branches:
      - master
jobs:
  build-deploy:
    name: build and depoy
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and Push
        uses: docker/build-push-action@v5
      - name: Stop
        run: docker stop kursovaya:latest
      - name: Deploy
        run: docker run -d -p 8080:8080 kursovaya:latest
      
        
