name: CI/CD Pipline

on: 
   push:
      branches:
         - master
jobs:
   build-deploy:
      name: build and depoy
      runs-on: self-hosted
      steps:
         - name: Checkout code
           uses: actions/checkout@v3

